// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9D8yehuPO-YQZCwtL92Z5QXKuSz6r570',
    appId: '1:410326900971:web:31727f478b339403929eae',
    messagingSenderId: '410326900971',
    projectId: 'uniaccess-real',
    authDomain: 'uniaccess-real.firebaseapp.com',
    storageBucket: 'uniaccess-real.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_8NGaYcj2Zrtt_hvNerv4lp_8eHwQ5U',
    appId: '1:410326900971:android:65fdbba1ec39fd92929eae',
    messagingSenderId: '410326900971',
    projectId: 'uniaccess-real',
    storageBucket: 'uniaccess-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDljOAxeBbeuDyV0xjHQDnz2cQL2go8MeA',
    appId: '1:410326900971:ios:ec01b58aedada76c929eae',
    messagingSenderId: '410326900971',
    projectId: 'uniaccess-real',
    storageBucket: 'uniaccess-real.appspot.com',
    iosBundleId: 'com.example.flutterxfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDljOAxeBbeuDyV0xjHQDnz2cQL2go8MeA',
    appId: '1:410326900971:ios:d108f769835a11cd929eae',
    messagingSenderId: '410326900971',
    projectId: 'uniaccess-real',
    storageBucket: 'uniaccess-real.appspot.com',
    iosBundleId: 'com.example.flutterxfirebase.RunnerTests',
  );
}
